name: reco_restaurant
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  firebase_storage: ^12.4.10
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  path: ^1.9.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
